[theme]
# InsightGeoLab AI
primaryColor = "#29A645"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F5FA"
textColor = "#0C2B4E"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"
